### ISSUE TITLE
Don't commit your Slack API token

### ISSUE THREAD

**Issue by mikestreety** [athenainn/slack-history#1]
I've noticed that you have committed your _private_ Slack token and pushed it to an open, _public_ website. This isn't very good practise as it means anyone with the token could read/write data to your Slack channels. Information could include passwords, logins or what you think of _Sandra_ who works in HR.

**Where the token is:**
https://github.com/athenanike/slack-history/blob/master/slack.conf#L2

I would recommend you take the following steps to remove and secure this token as soon as possible - to avoid any embarrassment!
1. **[Generate a new token in Slack](https://api.slack.com/tokens)**. Make sure you don't commit this new one!
2. Follow this Github tutorial on  [how to remove sensitive information](https://help.github.com/articles/remove-sensitive-data/) from your repository

Be careful in future about committing sensitive information :smile:

![hackers-are-coming](https://cloud.githubusercontent.com/assets/354085/15983997/b9555ff4-2fb2-11e6-97ec-29670a0da91a.jpg)

**Comment by kloertm** [comment]
Hi mikestreety,

No worries, when I pushed the config, the token was re-issued immediately.
it's only used for showing what the field would looks like.
Anyways, Thanks for your concern.
